import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import {FormsModule} from '@angular/forms';
import {MatInputModule} from '@angular/material/input';
import {MatSelectModule} from '@angular/material/select';
import {MatFormFieldModule} from '@angular/material/form-field';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

interface Type {
  value: string;
  viewValue: string;
}

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, MatInputModule, MatSelectModule, MatFormFieldModule, FormsModule, RouterOutlet, RouterLink, RouterLinkActive],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})

export class HomeComponent {
  selected_type!: string;
  types: Type[] = [
    {value: 'bug', viewValue: 'Bug'},
    {value: 'bug_electric', viewValue: 'Bug Electric'},
    {value: 'bug_fairy', viewValue: 'Bug Fairy'},
    {value: 'bug_fighting', viewValue: 'Bug Fighting'},
    {value: 'bug_fire', viewValue: 'Bug Fire'},
    {value: 'bug_flying', viewValue: 'Bug Flying'},
    {value: 'bug_ghost', viewValue: 'Bug Ghost'},
    {value: 'bug_grass', viewValue: 'Bug Grass'},
    {value: 'bug_ground', viewValue: 'Bug Ground'},
    {value: 'bug_poison', viewValue: 'Bug Poison'},
    {value: 'bug_rock', viewValue: 'Bug Rock'},
    {value: 'bug_steel', viewValue: 'Bug Steel'},
    {value: 'bug_water', viewValue: 'Bug Water'},
    {value: 'dark', viewValue: 'Dark'},
    {value: 'dark_dragon', viewValue: 'Dark Dragon'},
    {value: 'dark_fighting', viewValue: 'Dark Fighting'},
    {value: 'dark_fire', viewValue: 'Dark Fire'},
    {value: 'dark_flying', viewValue: 'Dark Flying'},
    {value: 'dark_ghost', viewValue: 'Dark Ghost'},
    {value: 'dark_ice', viewValue: 'Dark Ice'},
    {value: 'dark_psychic', viewValue: 'Dark Psychic'},
    {value: 'dark_steel', viewValue: 'Dark Steel'},
    {value: 'dragon', viewValue: 'Dragon'},
    {value: 'dragon_electric', viewValue: 'Dragon Electric'},
    {value: 'dragon_fighting', viewValue: 'Dragon Fighting'},
    {value: 'dragon_fire', viewValue: 'Dragon Fire'},
    {value: 'dragon_flying', viewValue: 'Dragon Flying'},
    {value: 'dragon_ground', viewValue: 'Dragon Ground'},
    {value: 'dragon_ice', viewValue: 'Dragon Ice'},
    {value: 'dragon_psychic', viewValue: 'Dragon Psychic'},
    {value: 'electric', viewValue: 'Electric'},
    {value: 'electric_fairy', viewValue: 'Electric Fairy'},
    {value: 'electric_flying', viewValue: 'Electric Flying'},
    {value: 'electric_ghost', viewValue: 'Electric Ghost'},
    {value: 'electric_normal', viewValue: 'Electric Normal'},
    {value: 'electric_steel', viewValue: 'Electric Steel'},
    {value: 'fairy', viewValue: 'Fairy'},
    {value: 'fairy_flying', viewValue: 'Fairy Flying'},
    {value: 'fighting', viewValue: 'Fighting'},
    {value: 'fighting_dark', viewValue: 'Fighting Dark'},
    {value: 'fighting_flying', viewValue: 'Fighting Flying'},
    {value: 'fighting_ghost', viewValue: 'Fighting Ghost'},
    {value: 'fighting_ice', viewValue: 'Fighting Ice'},
    {value: 'fighting_psychic', viewValue: 'Fighting Psychic'},
    {value: 'fighting_steel', viewValue: 'Fighting Steel'},
    {value: 'fire', viewValue: 'Fire'},
    {value: 'fire_dark', viewValue: 'Fire Dark'},
    {value: 'fire_dragon', viewValue: 'Fire Dragon'},
    {value: 'fire_fighting', viewValue: 'Fire Fighting'},
    {value: 'fire_flying', viewValue: 'Fire Flying'},
    {value: 'fire_ghost', viewValue: 'Fire Ghost'},
    {value: 'fire_ground', viewValue: 'Fire Ground'},
    {value: 'fire_normal', viewValue: 'Fire Normal'},
    {value: 'fire_psychic', viewValue: 'Fire Psychic'},
    {value: 'fire_rock', viewValue: 'Fire Rock'},
    {value: 'fire_steel', viewValue: 'Fire Steel'},
    {value: 'fire_water', viewValue: 'Fire Water'},
    {value: 'flying', viewValue: 'Flying'},
    {value: 'flying_dragon', viewValue: 'Flying Dragon'},
    {value: 'ghost', viewValue: 'Ghost'},
    {value: 'ghost_dark', viewValue: 'Ghost Dark'},
    {value: 'ghost_dragon', viewValue: 'Ghost Dragon'},
    {value: 'ghost_fairy', viewValue: 'Ghost Fairy'},
    {value: 'ghost_fire', viewValue: 'Ghost Fire'},
    {value: 'ghost_flying', viewValue: 'Ghost Flying'},
    {value: 'ghost_grass', viewValue: 'Ghost Grass'},
    {value: 'ghost_ground', viewValue: 'Ghost Ground'},
    {value: 'ghost_poison', viewValue: 'Ghost Poison'},
    {value: 'grass', viewValue: 'Grass'},
    {value: 'grass_dark', viewValue: 'Grass Dark'},
    {value: 'grass_fairy', viewValue: 'Grass Fairy'},
    {value: 'grass_fighting', viewValue: 'Grass Fighting'},
    {value: 'grass_flying', viewValue: 'Grass Flying'},
    {value: 'grass_ghost', viewValue: 'Grass Ghost'},
    {value: 'grass_ground', viewValue: 'Grass Ground'},
    {value: 'grass_ice', viewValue: 'Grass Ice'},
    {value: 'grass_poison', viewValue: 'Grass Poison'},
    {value: 'grass_psychic', viewValue: 'Grass Psychic'},
    {value: 'grass_steel', viewValue: 'Grass Steel'},
    {value: 'ground', viewValue: 'Ground'},
    {value: 'ground_dark', viewValue: 'Ground Dark'},
    {value: 'ground_dragon', viewValue: 'Ground Dragon'},
    {value: 'ground_electric', viewValue: 'Ground Electric'},
    {value: 'ground_flying', viewValue: 'Ground Flying'},
    {value: 'ground_ghost', viewValue: 'Ground Ghost'},
    {value: 'ground_psychic', viewValue: 'Ground Psychic'},
    {value: 'ground_rock', viewValue: 'Ground Rock'},
    {value: 'ground_steel', viewValue: 'Ground Steel'},
    {value: 'ice', viewValue: 'Ice'},
    {value: 'ice_flying', viewValue: 'Ice Flying'},
    {value: 'ice_ghost', viewValue: 'Ice Ghost'},
    {value: 'ice_ground', viewValue: 'Ice Ground'},
    {value: 'ice_psychic', viewValue: 'Ice Psychic'},
    {value: 'ice_water', viewValue: 'Ice Water'},
    {value: 'normal', viewValue: 'Normal'},
    {value: 'normal_dragon', viewValue: 'Normal Dragon'},
    {value: 'normal_fairy', viewValue: 'Normal Fairy'},
    {value: 'normal_fighting', viewValue: 'Normal Fighting'},
    {value: 'normal_flying', viewValue: 'Normal Flying'},
    {value: 'normal_grass', viewValue: 'Normal Grass'},
    {value: 'normal_ground', viewValue: 'Normal Ground'},
    {value: 'normal_psychic', viewValue: 'Normal Psychic'},
    {value: 'normal_water', viewValue: 'Normal Water'},
    {value: 'null', viewValue: 'Null'},
    {value: 'poison', viewValue: 'Poison'},
    {value: 'poison_bug', viewValue: 'Poison Bug'},
    {value: 'poison_dark', viewValue: 'Poison Dark'},
    {value: 'poison_dragon', viewValue: 'Poison Dragon'},
    {value: 'poison_fighting', viewValue: 'Poison Fighting'},
    {value: 'poison_fire', viewValue: 'Poison Fire'},
    {value: 'poison_flying', viewValue: 'Poison Flying'},
    {value: 'poison_ground', viewValue: 'Poison Ground'},
    {value: 'poison_water', viewValue: 'Poison Water'},
    {value: 'psychic', viewValue: 'Psychic'},
    {value: 'psychic_fairy', viewValue: 'Psychic Fairy'},
    {value: 'psychic_fighting', viewValue: 'Psychic Fighting'},
    {value: 'psychic_fire', viewValue: 'Psychic Fire'},
    {value: 'psychic_flying', viewValue: 'Psychic Flying'},
    {value: 'psychic_ghost', viewValue: 'Psychic Ghost'},
    {value: 'psychic_grass', viewValue: 'Psychic Grass'},
    {value: 'psychic_steel', viewValue: 'Psychic Steel'},
    {value: 'rock', viewValue: 'Rock'},
    {value: 'rock_bug', viewValue: 'Rock Bug'},
    {value: 'rock_dark', viewValue: 'Rock Dark'},
    {value: 'rock_dragon', viewValue: 'Rock Dragon'},
    {value: 'rock_fairy', viewValue: 'Rock Fairy'},
    {value: 'rock_fighting', viewValue: 'Rock Fighting'},
    {value: 'rock_flying', viewValue: 'Rock Flying'},
    {value: 'rock_grass', viewValue: 'Rock Grass'},
    {value: 'rock_ground', viewValue: 'Rock Ground'},
    {value: 'rock_ice', viewValue: 'Rock Ice'},
    {value: 'rock_poison', viewValue: 'Rock Poison'},
    {value: 'rock_psychic', viewValue: 'Rock Psychic'},
    {value: 'rock_steel', viewValue: 'Rock Steel'},
    {value: 'rock_water', viewValue: 'Rock Water'},
    {value: 'steel', viewValue: 'Steel'},
    {value: 'steel_dragon', viewValue: 'Steel Dragon'},
    {value: 'steel_fairy', viewValue: 'Steel Fairy'},
    {value: 'steel_fighting', viewValue: 'Steel Fighting'},
    {value: 'steel_flying', viewValue: 'Steel Flying'},
    {value: 'steel_ghost', viewValue: 'Steel Ghost'},
    {value: 'steel_ground', viewValue: 'Steel Ground'},
    {value: 'steel_psychic', viewValue: 'Steel Psychic'},
    {value: 'steel_rock', viewValue: 'Steel Rock'},
    {value: 'water', viewValue: 'Water'},
    {value: 'water_bug', viewValue: 'Water Bug'},
    {value: 'water_dark', viewValue: 'Water Dark'},
    {value: 'water_dragon', viewValue: 'Water Dragon'},
    {value: 'water_electric', viewValue: 'Water Electric'},
    {value: 'water_fairy', viewValue: 'Water Fairy'},
    {value: 'water_fighting', viewValue: 'Water Fighting'},
    {value: 'water_flying', viewValue: 'Water Flying'},
    {value: 'water_ghost', viewValue: 'Water Ghost'},
    {value: 'water_grass', viewValue: 'Water Grass'},
    {value: 'water_ground', viewValue: 'Water Ground'},
    {value: 'water_ice', viewValue: 'Water Ice'},
    {value: 'water_poison', viewValue: 'Water Poison'},
    {value: 'water_psychic', viewValue: 'Water Psychic'},
    {value: 'water_rock', viewValue: 'Water Rock'},
    {value: 'water_steel', viewValue: 'Water Steel'},
  ];
}
